# 1. Build biliup's web-ui
FROM node:lts AS webui-builder
# --- CN 加速 ---
RUN npm config set registry https://mirrors.tuna.tsinghua.edu.cn/npm/

COPY . /biliup
WORKDIR /biliup

RUN set -eux; \
    npm install; \
    npm run build

# 2. Build biliup's python wheel
FROM rust:latest AS wheel-builder
# --- CN 加速 ---
RUN mkdir -p $HOME/.cargo && \
    echo '[source.crates-io]\nreplace-with = "tuna"\n[source.tuna]\nregistry = "https://mirrors.tuna.tsinghua.edu.cn/git/crates.io-index.git"' > $HOME/.cargo/config.toml

RUN set -eux; \
    apt-get update; \
    apt-get install -y --no-install-recommends python3-pip g++; \
    pip3 install maturin --break-system-packages -i https://pypi.tuna.tsinghua.edu.cn/simple

COPY . /biliup
COPY --from=webui-builder /biliup/out /biliup/out
WORKDIR /biliup

RUN set -eux; \
    maturin build --release

# 3. Deploy Biliup
FROM python:3.13-slim AS biliup
# --- CN 加速 ---
RUN sed -i 's/deb.debian.org/mirrors.tuna.tsinghua.edu.cn/g' /etc/apt/sources.list.d/debian.sources

ENV TZ="Asia/Shanghai"
ENV LANG="C.UTF-8"
EXPOSE 19159/tcp
VOLUME /opt

COPY --from=wheel-builder /biliup/target/wheels/* /tmp/

RUN set -eux; \
    whl=$(ls /tmp/biliup*.whl); \
    pip3 install --no-cache-dir "$whl" -i https://pypi.tuna.tsinghua.edu.cn/simple; \
    pip3 cache purge; \
    rm -rf /tmp/*

RUN set -eux; \
    savedAptMark="$(apt-mark showmanual)"; \
    apt-get update; \
    apt-get install -y --no-install-recommends wget curl xz-utils g++; \
    # 此处 FFmpeg 若下载慢，建议改为 apt-get install -y ffmpeg
    apt-get install -y ffmpeg; \
    pip3 install --no-cache-dir quickjs -i https://pypi.tuna.tsinghua.edu.cn/simple; \
    apt-get purge -y --auto-remove; \
    rm -rf /var/lib/apt/lists/*

WORKDIR /opt
ENTRYPOINT ["biliup"]